### ISSUE TITLE
Documentation links inside the registry are not working

### ISSUE THREAD

**Issue by filol** [hashicorp/terraform-aws-terraform-enterprise-hvd#8]
When I access this module via the official registry page (https://registry.terraform.io/modules/hashicorp/terraform-enterprise-hvd/aws/latest), the links like:

📝 Note: See the [TFE Bootstrap Secrets](https://registry.terraform.io/modules/hashicorp/terraform-enterprise-hvd/aws/docs/tfe-bootstrap-secrets) doc for more details on how these secrets should be stored in AWS Secrets Manager.

are not working. They lead to a 404 page. But they are working on Github.

**Comment by ml4** [comment]
Hello @filol thanks so much for reporting this! I'll take a look now.

**Comment by roooms** [comment]
Hi @filol, thank you for bringing this to our attention. The Terraform Registry doesn't support relative URLs when it displays the main README so we will determine the best approach to address this and push a fix.

**Comment by roooms** [comment]
Hi @filol, we have found a solution to this issue which we are using on all _future_ releases of all HVD Modules.

We wanted to implement something that meant you saw the exact version of the module code/docs when you jump over to GitHub, rather than always linking to the main branch and potentially seeing content that is ahead of the specific release you were looking at in the Terraform Registry.

Specifically for this module, when we create the 0.2.0 release, it will include hardcoded links to the 0.2.0 tagged version of the GitHub files. We don't plan to back port this fix to the 0.1.0 releases as we will encourage all users to quickly move to the 0.2.0 release with additional improvements we have added from user feedback.

**Comment by roooms** [comment]
Hi again @filol,

We have just released 0.2.0 of this module and I have checked the links in the README now point to a specific (0.2.0) release and therefore work on the Terraform Registry. You can access the 0.2.0 release at https://registry.terraform.io/modules/hashicorp/terraform-enterprise-hvd/aws/0.2.0 or (for now) https://registry.terraform.io/modules/hashicorp/terraform-enterprise-hvd/aws/latest

I'll close this issue. Please be aware that we haven't fixed all the HVD Modules releases with this solution yet. As mentioned before, we will do this as we release new versions of each.

Please let us know if you find any other issues. We appreciate the feedback.

Thanks,
Dan
